"""empty message

Revision ID: a5c6bf2ae68a
Revises: d63b9cd5b93d
Create Date: 2023-06-29 12:57:58.239167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c6bf2ae68a'
down_revision = 'd63b9cd5b93d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('added_on')
        batch_op.drop_column('length')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('added_on', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###
